# Default values for kubelet-rubber-stamp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

serviceAccount:
  create: true

namespace: kube-system

watchNamespace: default

watchCSROrg: system:nodes

watchCSRCommonName: node

image:
  repository: weizhi/ckapprover
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

resources:
  requests:
    cpu: 100m
    memory: 50Mi
  limits:
    cpu: 100m
    memory: 50Mi

affinity: {}
